# Generated by Django 5.0.6 on 2024-05-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=20),
        ),
    ]
