# Generated by Django 5.0.6 on 2024-05-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainy', '0002_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
