# Generated by Django 5.0.6 on 2024-05-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainy', '0003_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
