# Generated by Django 5.0.6 on 2024-05-23 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainy', '0005_alter_profile_gender_scanhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanhistory',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
