# Generated by Django 5.0.6 on 2024-05-23 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainy', '0006_alter_scanhistory_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanhistory',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brainy.profile'),
        ),
    ]
