# Generated by Django 5.0.6 on 2024-05-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainy', '0007_alter_scanhistory_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanhistory',
            old_name='Profile',
            new_name='profile',
        ),
    ]
